name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/configure-pages@v2
      - name: Create dist directory and copy files to root
        run: |
          mkdir -p dist
          cp -r help/.vitepress/dist/* dist/
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist 
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
